### ISSUE TITLE
repeatDocPart fails if commented area contains images

### ISSUE THREAD

**Issue by ynaciri** [verronpro/docx-stamper#115]
**Describe the bug**
When using repeatDocPart, images are handled correctly if they're inserted through placeholder replacement during sub doc part generation and imported back in the main document.

On the opposite, when the main document commented area contains an image, it is not extracted into the sub template and the comment processor fails.

**To Reproduce**
1. Create a template using repeatDocPart, with at least an image file inside the comment area
2. Stamp a document with datas for the repeatDocPart
3. Exception occurs during stamping

see RepeatDocPartWithImagesInSourceTest on branch `fix/repeatDocPart-images`

**Expected behavior**
The document should be generated with the image repeated for each sub doc part.

**Desktop (please complete the following information):**
 - docx-stamper version : 1.5.0-javax

**Additional context**
```
org.wickedsource.docxstamper.api.DocxStamperException: java.lang.RuntimeException: Unexpected error occured ! Skipping this comment

	at org.wickedsource.docxstamper.DocxStamper.stamp(DocxStamper.java:135)
	at org.wickedsource.docxstamper.DocxStamper.stamp(DocxStamper.java:109)
	at org.wickedsource.docxstamper.AbstractDocx4jTest.stampAndLoad(AbstractDocx4jTest.java:50)
	at org.wickedsource.docxstamper.RepeatDocPartWithImagesInSourceTest.shouldReplicateImageFromTheMainDocumentInTheSubTemplate(RepeatDocPartWithImagesInSourceTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: Unexpected error occured ! Skipping this comment
	at org.wickedsource.docxstamper.processor.repeat.RepeatDocPartProcessor.commitChanges(RepeatDocPartProcessor.java:91)
	at org.wickedsource.docxstamper.processor.CommentProcessorRegistry.runProcessors(CommentProcessorRegistry.java:86)
	at org.wickedsource.docxstamper.DocxStamper.processComments(DocxStamper.java:144)
	at org.wickedsource.docxstamper.DocxStamper.stamp(DocxStamper.java:128)
	... 30 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.docx4j.relationships.Relationship.getTarget()" because "r" is null
	at org.docx4j.openpackaging.parts.relationships.RelationshipsPart.getPart(RelationshipsPart.java:258)
	at org.wickedsource.docxstamper.util.DocumentUtil.getImageData(DocumentUtil.java:93)
	at org.wickedsource.docxstamper.util.DocumentUtil.getRunDrawingData(DocumentUtil.java:75)
	at org.wickedsource.docxstamper.util.DocumentUtil.walkObjects(DocumentUtil.java:47)
	at org.wickedsource.docxstamper.util.DocumentUtil.walkObjects(DocumentUtil.java:51)
	at org.wickedsource.docxstamper.util.DocumentUtil.prepareDocumentForInsert(DocumentUtil.java:30)
	at org.wickedsource.docxstamper.processor.repeat.RepeatDocPartProcessor.commitChanges(RepeatDocPartProcessor.java:87)
	... 33 more
```

**Comment by ynaciri** [comment]
fixed on master-javax since v1.6.0-javax
