### ISSUE TITLE
1.6.8 regression for unresolved type exception / failOnUnresolvedExpression

### ISSUE THREAD

**Issue by StefanLobbenmeierObjego** [verronpro/docx-stamper#343]
**Describe the bug**
In v1.6.7, having an unresolved type in the word document would be handled by failOnUnresolvedExpression set to false. Now in 1.6.8 the Exception thrown instead:

```
org.springframework.expression.spel.SpelEvaluationException: EL1005E: Type cannot be found 'java.lang.System'
	at org.wickedsource.docxstamper.el.DefaultEvaluationContextConfigurer.lambda$configureEvaluationContext$0(DefaultEvaluationContextConfigurer.java:28)
	at org.springframework.expression.spel.ExpressionState.findType(ExpressionState.java:181)
	at org.springframework.expression.spel.ast.TypeReference.getValueInternal(TypeReference.java:70)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:60)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:96)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:114)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:273)
	at org.wickedsource.docxstamper.el.ExpressionResolver.resolve(ExpressionResolver.java:47)
	at org.wickedsource.docxstamper.processor.CommentProcessorRegistry.runProcessorsOnInlineContent(CommentProcessorRegistry.java:172)
	at org.wickedsource.docxstamper.processor.CommentProcessorRegistry$1.onParagraph(CommentProcessorRegistry.java:99)
	at org.wickedsource.docxstamper.util.walk.CoordinatesWalker.walk(CoordinatesWalker.java:35)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at org.wickedsource.docxstamper.util.walk.CoordinatesWalker.walk(CoordinatesWalker.java:25)
	at org.wickedsource.docxstamper.processor.CommentProcessorRegistry.runProcessors(CommentProcessorRegistry.java:102)
	at org.wickedsource.docxstamper.DocxStamper.processComments(DocxStamper.java:231)
	at org.wickedsource.docxstamper.DocxStamper.stamp(DocxStamper.java:212)
	at org.wickedsource.docxstamper.DocxStamper.stamp(DocxStamper.java:44)
	at pro.verron.officestamper.api.StreamStamper.stamp(StreamStamper.java:64)
```

**To Reproduce**

Create a word document with this content:
```java
${#{T(java.lang.System).exit(0)}
```

Call the docx stamper like this:

```kotlin
        val configuration = OfficeStamperConfigurations.standard()
        configuration.addTypeResolvers()
        configuration.setFailOnUnresolvedExpression(false)
        configuration.replaceUnresolvedExpressions(true)
        configuration.unresolvedExpressionsDefaultValue("_".repeat(10))
        val stamper = OfficeStampers.docxStamper(configuration)

        val byteArrayOutputStream = ByteArrayOutputStream()
        template.inputStream().use { templateInputStream ->
            byteArrayOutputStream.use { stamper.stamp(templateInputStream, templateContext, it) }
        }

        return byteArrayOutputStream.toByteArray()
```

**Expected behavior**
The unresolved type is replaced with 10 underscores

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: macOS
 - Java version: 21
 - docx4j version: 11.4.11
 - docx-stamper version 1.6.8

**Additional context**
I do not necessarily need this fixed, since I can just replace my unit test with an expected failure. Mentioning this in the release notes would be good enough if the change was intentional. If this change was accidental, then we should probably fix it.

**Comment by caring-coder** [comment]
It is probably an unintended bug, I'll add and fix this for a 1.6.9 version

**Comment by StefanLobbenmeierObjego** [comment]
yeah I mostly have this test case as just a check that this code never works with our current configuration, to make sure no templates can do bad stuff in our system 😄

**Comment by caring-coder** [comment]
Hey @StefanLobbenmeierObjego, would you mind a review of the PR to check if i didn't a particular use case ?

Test case 1
```java
/**
     * This method is a unit test for the `testStaticResolution` method. It uses parameterized testing with a CSV source
     * to test various scenarios.
     *
     * @param template         The template path
     * @param shouldFail       A boolean indicating whether the test should fail on unresolved expression
     * @param emptyOnError     A boolean indicating whether the test should leave empty on expression error
     * @param shouldReplace    A boolean indicating whether the test should replace unresolved expressions
     * @param replacementValue The replacement value for unresolved expressions
     * @param expected         The expected result of the test
     */
    @CsvSource(
            {
                    "System.exit.docx,false,false,false,Unresolved,${#{T(java.lang.System).exit(0)}",
                    "System.exit.docx,false,false,true,Unresolved,Unresolved",
                    "System.exit.docx,false,true,false,Unresolved,''",
                    "System.exit.docx,false,true,true,Unresolved,''",
                    "System.exit.docx,true,false,false,Unresolved,Should fail",
                    "System.exit.docx,true,false,true,Unresolved,Should fail",
                    "System.exit.docx,true,true,false,Unresolved,Should fail",
                    "System.exit.docx,true,true,true,Unresolved,Should fail",
            }
    )
    @ParameterizedTest
    void testStaticResolution(
            String template,
            boolean shouldFail,
            boolean emptyOnError,
            boolean shouldReplace,
            String replacementValue,
            String expected
    ) {
        var resource = getResource(Path.of(template));

        var configuration = OfficeStamperConfigurations.standard();
        configuration.setFailOnUnresolvedExpression(shouldFail);
        configuration.leaveEmptyOnExpressionError(emptyOnError);
        configuration.replaceUnresolvedExpressions(shouldReplace);
        configuration.unresolvedExpressionsDefaultValue(replacementValue);

        var stamper = new TestDocxStamper<>(configuration);
        if (shouldFail) {
            Executable executable = () -> stamper.stampAndLoadAndExtract(resource, new Object());
            assertThrows(OfficeStamperException.class, executable);
        }
        else {
            ThrowingSupplier<String> supplier = () -> stamper.stampAndLoadAndExtract(resource, new Object());
            assertEquals(expected, assertDoesNotThrow(supplier));
        }
    }

```

If you wish, you can find a second test case i added for more fin coverage in the PR.
Thank you for time if you do :)
